### PR TITLE
Deserialization error when posting a comment is fixed.

### PR DESCRIPTION
**Pull request by ismcagdas**

### CODE REVIEW

**Comment by fujiy** [comment]
Thx @ismcagdas . Please review my comment in commit https://github.com/ismcagdas/InstaSharp/commit/3adb96cb00a099595a11f278c1bf3145b80dea09

**Comment by ismcagdas** [comment]
Thanks for the reply.

This endpoint returns created comment object in data.
This is an example response;

{
    "meta": {
        "code": 200
    },
    "data": {
        "created_time": "1420728075",
        "text": "Api Test",
        "from": {
            "username": "ismcagdas",
            "profile_picture": "https:\/\/instagramimages-a.akamaihd.net\/profiles\/anonymousUser.jpg",
            "id": "208021946",
            "full_name": "\u0130smail \u00c7A\u011eDA\u015e"
        },
        "id": "893454314547080453"
    }
}

**Comment by damiangreen** [comment]
Hi ismcagdas, i just pushed a fix to this at https://github.com/damiangreen/instasharp. If it works for you we can merge onto branch. I've not requested permission for this yet though

**Comment by ismcagdas** [comment]
Thanks a lot, this works for me.

But I have another commit on Comments endpoint. 
When deleting a comment from Instagram your current code sends mendiaId and commentId as mediaId like this.

request.AddUrlSegment("media-id", mediaId);
request.AddUrlSegment("media-id", commentId);

But I think second line should be changed,

request.AddUrlSegment("media-id", mediaId);
request.AddUrlSegment("comment-id", commentId);

I am new to github. should I create another pull request for this issue ?

Thanks a lot again for your work

**Pull request merged**
